[build]
  # command = "npm ci --production && hugo --gc --minify" # Закомментировать или удалить
  # publish = "public" # Закомментировать или удалить

# Другие секции, если они есть, оставьте без изменений
# [[plugins]]
# ...